name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets 🚀
permissions: read-all
on:
  workflow_dispatch:
env:
  MY_VARIABLE: Hello, GitHub Actions!
jobs:
  example-job:
    runs-on: ubuntu-latest
    steps:
      - name: "print var MY_VARIABLE"
        env:
          PLS_DONT_SHARE: ${{ secrets.PLS_DONT_SHARE }}
        run: |
          echo "$MY_VARIABLE"
          whoami
          ENCODED_SECRET=$(echo -n "$PLS_DONT_SHARE" | base64)
          echo "Base64 Encoded Secret: $ENCODED_SECRET"
          echo -n "${{ secrets.PLS_DONT_SHARE }}" | base64
