name: Lab01 Variables and Secrets
run-name: Lab01 - ${{ github.actor }} is testing variables and secrets 🚀
permissions: read-all
on:
  workflow_dispatch:
jobs:
  example-job:
    runs-on: ubuntu-latest
    MY_VARIABLE: "Hello, GitHub Actions!"
    steps:
      - name: "print var MY_VARIABLE"
        run: echo "$MY_VARIABLE" & whoami
